# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Run eslint with reviewdog
  # You may pin to the exact commit or the version.
  # uses: reviewdog/action-eslint@282bf9d07bc87c519d17ca3a70e94b54232b03e0
        uses: reviewdog/action-eslint@v1.14.0
        with:
          # GITHUB_TOKEN.
          github_token: # default is ${{ github.token }}
          # Report level for reviewdog [info,warning,error]
          level: # optional, default is error
          # Reporter of reviewdog command [github-check,github-pr-review]. Default is github-pr-review. github-pr-review can use Markdown and add a link to rule page in reviewdog reports.

    reporter: # optional, default is github-pr-review
    # Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
Default is added.

    filter_mode: # optional, default is added
    # Exit code for reviewdog when errors are found [true,false]
Default is `false`.

    fail_on_error: # optional, default is false
    # Additional reviewdog flags
    reviewdog_flags: # optional, default is 
    # flags and args of eslint command. Default: '.'
    eslint_flags: # optional, default is .
    # The directory from which to look for and run eslint. Default '.'
    workdir: # optional, default is .
    # Tool name to use for reviewdog reporter
    tool_name: # optional, default is eslint
